# Generated by Django 2.0 on 2020-08-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hacker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('no_challenges', models.IntegerField()),
                ('except_level', models.IntegerField()),
                ('Data_structures', models.IntegerField()),
                ('Algo', models.IntegerField()),
                ('cpp', models.IntegerField()),
                ('java', models.IntegerField()),
                ('python', models.IntegerField()),
                ('votes', models.IntegerField()),
            ],
        ),
    ]
