# Generated by Django 2.0 on 2020-08-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hacker',
            name='Name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
