# Generated by Django 2.0 on 2020-08-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20200807_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='hacker',
            name='code',
            field=models.IntegerField(default=12, unique=True),
            preserve_default=False,
        ),
    ]
